try {
    hello()
} catch (err) {
    console.log(Error(err))
}